services:
  core-api:
    image: core-api
    container_name: core-api
    build: ./src/backend/core-api
    ports:
      - '${CORE_API_PORT}:${CORE_API_PORT}'
    environment:
      CORE_API_PORT: ${CORE_API_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      DOMAIN_PROD: ${DOMAIN_PROD}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - api_network
    command: sh -c "yarn prisma migrate deploy && yarn prisma generate && yarn start:prod"

  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - api_network

volumes:
  postgres_data:

networks:
  api_network:
    driver: bridge
